force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SurperBadge</fullName>
            </value>
            <value>
                <fullName>Apex Specialist</fullName>
            </value>
            <value>
                <fullName>Lightning Specialist</fullName>
            </value>
            <value>
                <fullName>Aura Specialist</fullName>
            </value>
            <value>
                <fullName>Admin Specialist</fullName>
            </value>
            <value>
                <fullName>Pordot Specialist</fullName>
            </value>
            <value>
                <fullName>Data Loader Specialist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CourseCreateController.cls
public with sharing class CourseCreateController {
    public CourseCreateController() {

    }

    @AuraEnabled 
    public static Map<String, String> getCategoryFieldValue(){
        Map<String, String> options = new Map<String, String>();
        
        Schema.DescribeFieldResult fieldResult = Course__c.Category__c.getDescribe();
        
        List<Schema.PicklistEntry> pValues = fieldResult.getPicklistValues();
        for (Schema.PicklistEntry p: pValues) {
            
            options.put(p.getValue(), p.getLabel());
        }
        return options;
    }
    
}