force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SurperBadge</fullName>
            </value>
            <value>
                <fullName>Apex Specialist</fullName>
            </value>
            <value>
                <fullName>Lightning Specialist</fullName>
            </value>
            <value>
                <fullName>Aura Specialist</fullName>
            </value>
            <value>
                <fullName>Admin Specialist</fullName>
            </value>
            <value>
                <fullName>Pordot Specialist</fullName>
            </value>
            <value>
                <fullName>Data Loader Specialist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Completion__c.field-meta.xml
<CustomField>
    <fullName>Completion__c</fullName>
    <label>Completion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/CourseLevel__c.field-meta.xml
<CustomField>
    <fullName>CourseLevel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Level</label>
    <referenceTo>CourseLevel__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/CoursePosition__c.field-meta.xml
<CustomField>
    <fullName>CoursePosition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CoursePosition</label>
    <referenceTo>CoursePosition__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseLevel__c/CourseLevel__c.object-meta.xml
<CustomObject>
    <label>CourseLevel</label>
    <nameField>
        <label>CourseLevel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CourseLevels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CoursePosition__c/CoursePosition__c.object-meta.xml
<CustomObject>
    <label>CoursePosition</label>
    <nameField>
        <label>CoursePosition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CoursePositions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CourseSearchResultsTest.cls
@isTest
public with sharing class CourseSearchResultsTest {
    public CourseSearchResultsTest() {

    }

    @TestSetup
    static void initData(){
        Account account = new Account(
                Name = 'Facebook'
        );
        insert account;
        Contact contact = new Contact(
                AccountId = account.Id,
                LastName = 'Karl'
        );
        insert contact;

        Profile p = [SELECT Id FROM Profile WHERE Name = 'System Administrator'];
        User u = new User(Alias = 'standt', Email = 'standarduser@testorg.com',
            EmailEncodingKey = 'UTF-8', LastName = 'Testing', LanguageLocaleKey = 'en_US',
            LocaleSidKey = 'en_US', ProfileId = p.Id,
            TimeZoneSidKey = 'America/Los_Angeles', UserName = 'testsystemadmin@test.com');
        insert u;

        CoursePosition__c cp = new CoursePosition__c(
            Name = 'Software Engineering'
        );

        insert cp;

        CourseLevel__c cl = new CourseLevel__c(
            Name = 'Level 4'
        );
        insert cl;

        List<Course__c> courseList = new List<Course__c>();
        
        for(Integer i=0; i < 10; i++){
            Course__c co = new Course__c();
            co.Contact__c = contact.Id;
            co.CourseLevel__c = cl.Id;
            co.CoursePosition__c = cp.Id;
            co.Completion__c = 22;
            co.Category__c = 'SurperBadge';
            co.Description__c = 'testDescribe';
            co.isActive__c = true;
            co.User__c = u.Id;
            courseList.add(co);
        }

        insert courseList;
    }

    @isTest
    static void TestgetCoursesWithBothId(){
        User adminUser = [SELECT username, Id, Name FROM User WHERE username = 'testsystemadmin@test.com'];
        System.runas(adminUser){
            Test.startTest();
            List<CoursePosition__c> cpList = [SELECT Id, Name FROM CoursePosition__c LIMIT 5];
            List<CourseLevel__c> clList = [SELECT Id, Name FROM CourseLevel__c LIMIT 5];
            List<Course__c> result = CourseSearchResults.getCourses(clList[0].Id, cpList[0].Id);
            System.assertNotEquals(null, result);
            Test.stopTest();
        }
       
    }

    @isTest
    static void TestgetCoursesWithCLId(){
        Test.startTest();
        List<CoursePosition__c> cpList = [SELECT Id, Name FROM CoursePosition__c LIMIT 5];
        List<CourseLevel__c> clList = [SELECT Id, Name FROM CourseLevel__c LIMIT 5];

        List<Course__c> result = CourseSearchResults.getCourses(clList[0].Id, null);
        System.assertNotEquals(null, result);
        Test.stopTest();
    }

    @isTest
    static void TestgetCoursesWithCPId(){
        Test.startTest();
        List<CoursePosition__c> cpList = [SELECT Id, Name FROM CoursePosition__c LIMIT 5];
        List<CourseLevel__c> clList = [SELECT Id, Name FROM CourseLevel__c LIMIT 5];

        List<Course__c> result = CourseSearchResults.getCourses(null, cpList[0].Id);
        System.assertNotEquals(null, result);
        Test.stopTest();
    }

    @isTest
    static void TestgetCoursesWithoutId(){
        Test.startTest();
        List<CoursePosition__c> cpList = [SELECT Id, Name FROM CoursePosition__c LIMIT 5];
        List<CourseLevel__c> clList = [SELECT Id, Name FROM CourseLevel__c LIMIT 5];

        List<Course__c> result = CourseSearchResults.getCourses(null, null);
        System.assertNotEquals(null, result);
        Test.stopTest();
    }
}