force-app/main/default/objects/Course__c/Course__c.object-meta.xml
<CustomObject>
    <label>Course</label>
    <nameField>
        <label>Course Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Courses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Course__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SurperBadge</fullName>
            </value>
            <value>
                <fullName>Apex Specialist</fullName>
            </value>
            <value>
                <fullName>Lightning Specialist</fullName>
            </value>
            <value>
                <fullName>Aura Specialist</fullName>
            </value>
            <value>
                <fullName>Admin Specialist</fullName>
            </value>
            <value>
                <fullName>Pordot Specialist</fullName>
            </value>
            <value>
                <fullName>Data Loader Specialist</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Course__c/fields/Completion__c.field-meta.xml
<CustomField>
    <fullName>Completion__c</fullName>
    <label>Completion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/CourseLevel__c.field-meta.xml
<CustomField>
    <fullName>CourseLevel__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Course Level</label>
    <referenceTo>CourseLevel__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/CoursePosition__c.field-meta.xml
<CustomField>
    <fullName>CoursePosition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CoursePosition</label>
    <referenceTo>CoursePosition__c</referenceTo>
    <relationshipLabel>Courses</relationshipLabel>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/img_link__c.field-meta.xml
<CustomField>
    <fullName>img_link__c</fullName>
    <label>img_link</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Course__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Courses</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CourseLevel__c/CourseLevel__c.object-meta.xml
<CustomObject>
    <label>CourseLevel</label>
    <nameField>
        <label>CourseLevel Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CourseLevels</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CoursePosition__c/CoursePosition__c.object-meta.xml
<CustomObject>
    <label>CoursePosition</label>
    <nameField>
        <label>CoursePosition Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CoursePositions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CourseSearchResults.cls
/****************************************************
 * @ apex course record query controller
 * get all records
 * 
 ****/
public with sharing class CourseSearchResults {

    @AuraEnabled
    public static List<Course__c> getCourses(string courseLevelId, String coursePositionId){
        try {
            if(!String.isBlank(courseLevelId) && !String.isBlank(coursePositionId)){
                return [SELECT  Id, 
                                Name, 
                                CourseLevel__c, 
                                CourseLevel__r.Name, 
                                Contact__r.Name, 
                                CoursePosition__c, 
                                CoursePosition__r.Name,   
                                Description__c, 
                                img_link__c, 
                                Completion__c, 
                                Category__c,
                                Picture__c,
                                User__c
                                
                        FROM Course__c 
                        WHERE CourseLevel__c =: courseLevelId 
                        AND CoursePosition__c =: coursePositionId  
                        AND User__c =: UserInfo.getUserId() 
                        ORDER BY Name];
            }
            else if(!String.isBlank(courseLevelId)){
                return [SELECT  Id, 
                                Name, 
                                CourseLevel__c, 
                                CourseLevel__r.Name, 
                                Contact__r.Name, 
                                CoursePosition__c, 
                                CoursePosition__r.Name,  
                                Description__c, 
                                img_link__c, 
                                Completion__c, 
                                Category__c,
                                Picture__c,
                                User__c
                                
                FROM Course__c 
                WHERE CourseLevel__c =: courseLevelId 
                AND User__c =: UserInfo.getUserId() 
                ORDER BY Name];
            }
            else if(!String.isBlank(coursePositionId)){
                return [SELECT 
                                Id, 
                                Name, 
                                CourseLevel__c, 
                                CourseLevel__r.Name, 
                                Contact__r.Name, 
                                CoursePosition__c, 
                                CoursePosition__r.Name,  
                                Description__c, 
                                img_link__c, 
                                Completion__c, 
                                Category__c,
                                Picture__c,
                                User__c
                        FROM Course__c 
                        WHERE CoursePosition__c =: coursePositionId 
                        AND User__c =: UserInfo.getUserId() 
                        ORDER BY Name];
            }
            else{
                return [SELECT 
                                Id, 
                                Name, 
                                CourseLevel__c, 
                                CourseLevel__r.Name, 
                                Contact__r.Name, 
                                CoursePosition__c, 
                                CoursePosition__r.Name,  
                                Description__c, 
                                img_link__c, 
                                Completion__c, 
                                Category__c,
                                Picture__c,
                                User__c
                FROM Course__c 
                WHERE User__c =: UserInfo.getUserId()  
                ORDER BY Name];
            }
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}